// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rstn,0,0);
        VL_IN8(s_axis_tvalid,0,0);
        VL_OUT8(s_axis_tready,0,0);
        VL_IN8(s_axis_tlast,0,0);
        VL_OUT8(m_axis_tvalid,0,0);
        VL_IN8(m_axis_tready,0,0);
        VL_OUT8(m_axis_tlast,0,0);
        VL_OUT8(irq,0,0);
        CData/*0:0*/ NTT_axis_ip__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__rstn;
        CData/*0:0*/ NTT_axis_ip__DOT__s_axis_tvalid;
        CData/*0:0*/ NTT_axis_ip__DOT__s_axis_tready;
        CData/*0:0*/ NTT_axis_ip__DOT__s_axis_tlast;
        CData/*0:0*/ NTT_axis_ip__DOT__m_axis_tvalid;
        CData/*0:0*/ NTT_axis_ip__DOT__m_axis_tready;
        CData/*0:0*/ NTT_axis_ip__DOT__m_axis_tlast;
        CData/*0:0*/ NTT_axis_ip__DOT__irq;
        CData/*0:0*/ NTT_axis_ip__DOT__self_valid;
        CData/*0:0*/ NTT_axis_ip__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ready_for_next_batch;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__state;
        CData/*1:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__empty;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__wr_ptr;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__rd_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__empty;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__wr_ptr;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__rd_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__stall_i;
    };
    struct {
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__state;
        CData/*2:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__empty;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__wr_ptr;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__rd_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__empty;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__wr_ptr;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__rd_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__state;
        CData/*3:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__empty;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__wr_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__rd_ptr;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__empty;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__wr_ptr;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__rd_ptr;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__stall_i;
    };
    struct {
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__state;
        CData/*4:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__empty;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__wr_ptr;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__rd_ptr;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__empty;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__wr_ptr;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__rd_ptr;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__state;
        CData/*5:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__empty;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__wr_ptr;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__rd_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__empty;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__wr_ptr;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__rd_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__occupancy;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__stall_i;
    };
    struct {
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__state;
        CData/*6:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__empty;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__wr_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__rd_ptr;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__empty;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__wr_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__rd_ptr;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__clk_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__rst_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__valid_o;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2_wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2_rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2_empty;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__state;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__counter;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__fifo_change;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__empty;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__wr_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__rd_ptr;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__wr_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__full;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__rd_en;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__empty;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__wr_ptr;
        CData/*7:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__rd_ptr;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__stall_i;
    };
    struct {
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__stall_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__stall;
    };
    struct {
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__clk;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__rst;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_i;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__stall;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_out;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_s1;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_s2;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_s3;
        CData/*0:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__valid_s4;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__clk__0;
        SData/*15:0*/ NTT_axis_ip__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_1;
    };
    struct {
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_5;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_6;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__tf_data_7;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT____Vlvbound_h8a7aa62c__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT____Vlvbound_hee33f2d9__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT____Vlvbound_h8a7aa62c__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT____Vlvbound_hee33f2d9__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT____Vlvbound_h8a7aa62c__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT____Vlvbound_hee33f2d9__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT____Vlvbound_h8a7aa62c__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT____Vlvbound_hee33f2d9__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT____Vlvbound_h90d4b78f__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT____Vlvbound_h54553fc6__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT____Vlvbound_h90d4b78f__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT____Vlvbound_h54553fc6__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT____Vlvbound_h90d4b78f__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT____Vlvbound_h54553fc6__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT____Vlvbound_h90d4b78f__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT____Vlvbound_h54553fc6__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT____Vlvbound_he4b35351__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT____Vlvbound_h1082318e__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT____Vlvbound_he4b35351__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT____Vlvbound_h1082318e__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT____Vlvbound_he4b35351__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT____Vlvbound_h1082318e__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT____Vlvbound_he4b35351__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT____Vlvbound_h1082318e__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__b_i;
    };
    struct {
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT____Vlvbound_h3187fd02__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT____Vlvbound_h6f7d556c__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT____Vlvbound_h3187fd02__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT____Vlvbound_h6f7d556c__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__rd_data;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT____Vlvbound_h3187fd02__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT____Vlvbound_h6f7d556c__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT____Vlvbound_h3187fd02__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT____Vlvbound_h6f7d556c__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__rd_data;
        SData/*8:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__occupancy;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT____Vlvbound_h04e46552__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT____Vlvbound_h73b094e5__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT____Vlvbound_h04e46552__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT____Vlvbound_h73b094e5__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__rd_data;
        SData/*8:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__occupancy;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT____Vlvbound_h04e46552__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT____Vlvbound_h73b094e5__0;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT____Vlvbound_h04e46552__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT____Vlvbound_h73b094e5__1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2_data_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__rd_data;
        SData/*8:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__occupancy;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__rd_data;
        SData/*8:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__occupancy;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__addr;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__dout;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_s2;
    };
    struct {
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_s1;
    };
    struct {
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__a_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__b_i;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__w;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__b_o;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_s1;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__m_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_s2;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_s3;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__bw_s4;
        SData/*15:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__a_s4;
        VL_IN(s_axis_tdata,31,0);
        VL_OUT(m_axis_tdata,31,0);
        IData/*31:0*/ NTT_axis_ip__DOT__s_axis_tdata;
        IData/*31:0*/ NTT_axis_ip__DOT__m_axis_tdata;
        IData/*31:0*/ NTT_axis_ip__DOT__in_data_count;
        IData/*31:0*/ NTT_axis_ip__DOT__out_data_count;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2_data_i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__i;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__wr_data;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__i;
    };
    struct {
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__mult_s1;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__mult_s2;
        IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__t_s3;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__add_temp;
        IData/*16:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__sub_temp;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__BU_DU_bus_a;
        VlUnpacked<SData/*15:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__BU_DU_bus_b;
        VlUnpacked<SData/*15:0*/, 7> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_bus_a;
        VlUnpacked<SData/*15:0*/, 7> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_bus_b;
        VlUnpacked<CData/*0:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__BU_DU_valid;
        VlUnpacked<CData/*0:0*/, 7> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_valid;
        VlUnpacked<CData/*0:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_valid_D;
        VlUnpacked<SData/*15:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_bus_a_D;
        VlUnpacked<SData/*15:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__DU_BU_bus_b_D;
        VlUnpacked<SData/*15:0*/, 7> NTT_axis_ip__DOT__ntt_inst__DOT__tf_addr;
        VlUnpacked<SData/*15:0*/, 12> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 12> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 16> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 16> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 28> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 28> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 52> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 52> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 100> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 100> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 196> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 196> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 256> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__mem;
    };
    struct {
        VlUnpacked<SData/*15:0*/, 256> NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 2> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__mem;
        VlUnpacked<SData/*15:0*/, 4> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__mem;
        VlUnpacked<SData/*15:0*/, 8> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__mem;
        VlUnpacked<SData/*15:0*/, 16> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__mem;
        VlUnpacked<SData/*15:0*/, 32> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__mem;
        VlUnpacked<SData/*15:0*/, 64> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__mem;
        VlUnpacked<SData/*15:0*/, 128> NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__C_AXIS_TDATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__N = 0x00000100U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__STAGES = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__STAGE = 1U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__DEPTH = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__DEPTH = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__MEM_DEPTH = 0x0000000cU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_1__DOT__PTR_W = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__DEPTH = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__MEM_DEPTH = 0x0000000cU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_1__DOT__buffer_2__DOT__PTR_W = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__STAGE = 2U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__MEM_DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_1__DOT__PTR_W = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__MEM_DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_2__DOT__buffer_2__DOT__PTR_W = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__STAGE = 3U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__DEPTH = 0x0000000eU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__DEPTH = 0x0000000eU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__MEM_DEPTH = 0x0000001cU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_1__DOT__PTR_W = 5U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__DEPTH = 0x0000000eU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__MEM_DEPTH = 0x0000001cU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_3__DOT__buffer_2__DOT__PTR_W = 5U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__STAGE = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__DEPTH = 0x0000001aU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__DEPTH = 0x0000001aU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__MEM_DEPTH = 0x00000034U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_1__DOT__PTR_W = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__DEPTH = 0x0000001aU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__MEM_DEPTH = 0x00000034U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_4__DOT__buffer_2__DOT__PTR_W = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__STAGE = 5U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__DEPTH = 0x00000032U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__DEPTH = 0x00000032U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__MEM_DEPTH = 0x00000064U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_1__DOT__PTR_W = 7U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__DEPTH = 0x00000032U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__MEM_DEPTH = 0x00000064U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_5__DOT__buffer_2__DOT__PTR_W = 7U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__STAGE = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__DEPTH = 0x00000062U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__DEPTH = 0x00000062U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__MEM_DEPTH = 0x000000c4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_1__DOT__PTR_W = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__DEPTH = 0x00000062U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__MEM_DEPTH = 0x000000c4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_6__DOT__buffer_2__DOT__PTR_W = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__STAGE = 7U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__DEPTH = 0x00000080U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__N = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__DEPTH = 0x00000080U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__MEM_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_1__DOT__PTR_W = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__DEPTH = 0x00000080U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__MEM_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__Delay_inst_7__DOT__buffer_2__DOT__PTR_W = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__STAGE = 1U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__DEPTH = 2U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_1__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f31, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__STAGE = 2U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__DEPTH = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_2__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f32, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__STAGE = 3U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_3__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f33, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__STAGE = 4U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_4__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f34, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__STAGE = 5U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__DEPTH = 0x00000020U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_5__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f35, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__STAGE = 6U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__DEPTH = 0x00000040U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_6__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f36, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__STAGE = 7U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__DEPTH = 0x00000080U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr VlWide<9>/*287:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__t_rom_7__DOT__INIT_FILE = VlWide<9>{{
            0x2e6d656d, 0x67655f37, 0x2f737461, 0x746f7273,
            0x65466163, 0x6964646c, 0x4c2f5477, 0x2e2f5254,
            0x2e2e2f2e
    }};
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__0__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__1__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__2__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__3__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__4__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__5__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__6__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__DATA_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__Q = 0x00000d01U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__Q_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__Q_INV = 0x00000cffU;
    static constexpr IData/*31:0*/ NTT_axis_ip__DOT__ntt_inst__DOT__butterfly_gen__BRA__7__KET____DOT__butterfly_inst__DOT__R_MASK = 0x0000ffffU;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
